license="${modLicense}"
#issueTrackerURL=
[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
#updateJSONURL=
#displayURL=
#logoFile=
#credits=
authors="FlarelabsMC"
description='''
Contains every module and internal API for Crypt of the Second Lord.
'''
[[mixins]]
config="${modId}.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.${modId}]]
    modId="neoforge"
    type="required"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    type="required"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="blazesdl"
    type="required"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${modId}]]
    modId="player_animation_library"
    type="required"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="shouldersurfing"
    type="required"
    ordering="NONE"
    side="BOTH"
#[features.${modId}]
#openGLVersion="[3.2,)"
